addSubstract Component
globant-trainings/pod6-ecommerce pull request #2
Opened 2022-05-19 13:30 UTC by solymdev

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ x ] Storybook

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-19 17:34 UTC, miguelromeroglb requested changes
Faltan los unit tests y hay unos comentarios que arreglar

2022-05-19 17:34 UTC, miguelromeroglb commented on .vscode/settings.json
> +    "workbench.colorCustomizations": {
Se necesita este archivo? creo que es alguna configuración propia de tu vscode, podrías excluirla del commit?

2022-05-19 17:34 UTC, miguelromeroglb commented on src/components/AddSubstract/addSubstract.css
> +.Button {
creo que estos estilos ya existen para el component botón, no se estarían sobreescribiendo?

2022-05-19 17:34 UTC, miguelromeroglb commented on src/components/AddSubstract/AddSubstract.jsx
> +          <button
Porque no usar elcomponent button que ya existe con los colores customizados?

2022-05-19 21:49 UTC, solymdev commented on .vscode/settings.json
> +    "workbench.colorCustomizations": {
Claro, excluyo la carpeta en el próximo pull request

2022-05-19 21:55 UTC, solymdev commented on src/components/AddSubstract/addSubstract.css
> +.Button {
Corregido

2022-05-19 21:55 UTC, solymdev commented on src/components/AddSubstract/AddSubstract.jsx
> +          <button
Listo

2022-05-26 15:18 UTC, miguelromeroglb approved these changes
LGTM

2022-06-06 14:56 UTC, miguelromeroglb approved these changes

2022-06-06 15:31 UTC, merged